version: '3'
services:
  apache:
    build: ./websrv
    container_name: "tl3_websrv"
    volumes:
      - ./src/frontend/:/usr/local/apache2/htdocs/
      - ./src/backend/:/usr/local/apache2/cgi-bin/
    ports:
      - "8080:80"
    links:
      - postgres

  postgres:
    build: ./db
    container_name: "tl3_db"
    volumes:
      - /db/data:/volume
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=tl3
      - PGDATA=/volume/data
