version: '3'
services:
  postgres:
    build: ./db
    container_name: "tl3_ms_db"
    volumes:
      - ${PWD}/db/data:/volume
    ports:
      - "5550:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=tl3
      - PGDATA=/volume/data

  nginx:
    image: nginx:1.15
    restart: always
    container_name: "nginx"
    ports:
      - 8000:80
    volumes:
      - ./balancer:/etc/nginx/conf.d:ro
    depends_on:
      - users
      - trabajos
      - login
    
  users:
    build: ./src/users
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
    links:
      - postgres

  trabajos:
    build: ./src/trabajos
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
    links:
      - postgres

  login:
    build: ./src/login
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
    links:
      - postgres

    #networks:
    #  - nginx_network
    # esto solo funciona con swarm
    #deploy:
    #  replicas: 5x
    #  restart_policy:
    #    condition: on-failure
    #  resources:
    #    limits:
    #      cpus: "0.1"
    #      memory: 50M      